log:
  level: "debug"
  encoding: "json"

auth:
  issuer: "http://localhost:8090/realms/astigo"
  client_id: "astigo-api"

http:
  port: 8080
  mode: "debug"

grpc:
  port: 50051

telemetry:
  url: "localhost:4318"
  service_name: "astigo"


postgres:
  host: "localhost"
  port: 5432
  user: "astigo"
  password: "astigo_password"
  dbname: "astigo"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  max_lifetime: 300
  migrate: true
  migrations_path: "file://migrations/postgres"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

nats:
  url: "nats://localhost:4222"
  username: ""
  password: ""

s3:
  bucket: "default"
  session_token: ""
  use_path_style: true
  server_side_encryption: ""
  default_cache_control: ""
  upload_part_size: 0
  timeout: "10s"